<a href="https://colab.research.google.com/github/gandepallichandini2003/GANDEPALLI-CHANDINI/blob/main/CLEANING_AND_PREPROCESSING_PANDAS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**DATA CLEANING**

Handle Missing Values

Check missing values

In [2]:
import pandas as pd
df = pd.DataFrame({'A': [1, 2, None], 'B': [4, None, 6]})
df.isnull().sum()

A    1
B    1
dtype: int64

Fill missing values

In [3]:
df.fillna(method='ffill', inplace=True)  # forward fill

/tmp/ipykernel_1070/103086618.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill', inplace=True)  # forward fill

Remove Duplicate Rows

In [5]:
df = df.drop_duplicates()

Handle Incorrect Values

In [7]:
import numpy as np
df.replace(['?', 'NA', 'null'], np.nan, inplace=True)

**DATA PREPARATION STEPS**

Feature Selection

In [9]:
df = pd.DataFrame({
    'patient_id': [1, 2, 3, 4, 5],
    'age': [30, 45, 22, 58, 37],
    'gender': ['Male', 'Female', 'Female', 'Male', 'Female'],
    'disease': ['Flu', 'Cold', 'Flu', 'Allergy', 'Cold'],
    'treatment': ['A', 'B', 'A', 'C', 'B'],
    'other_column': [10, 20, 30, 40, 50]
})
df = df[['patient_id', 'age', 'gender', 'disease', 'treatment']]

Encode Categorical Data

In [10]:
df['gender'] = df['gender'].map({'Male': 0, 'Female': 1})

Final Clean Check

In [11]:
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   patient_id  5 non-null      int64
 1   age         5 non-null      int64
 2   gender      5 non-null      int64
 3   disease     5 non-null      object
 4   treatment   5 non-null      object
dtypes: int64(3), object(2)
memory usage: 332.0+ bytes

patient_id    0
age           0
gender        0
disease       0
treatment     0
dtype: int64

Save Cleaned Dataset

In [12]:
df.to_excel('cleaned_hospital_data.xlsx', index=False)