<a href="https://colab.research.google.com/github/gandepallichandini2003/GANDEPALLI-CHANDINI/blob/main/REMOVING_PANDAS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**REMOVING DUPLICATES**

**Import Pandas**

In [1]:
import pandas as pd

**Load the Dataset**

In [3]:
df = pd.read_excel('/hospital data analysis dataset.xlsx')

**Display Data**

In [4]:
df.head()

,Patient_ID,Age,Gender,Condition,Procedure,Cost,Length_of_Stay,Readmission,Outcome,Satisfaction
0,1,45,Female,Heart Disease,Angioplasty,15000,5,No,Recovered,4
1,2,60,Male,Diabetes,Insulin Therapy,2000,3,Yes,Stable,3
2,3,32,Female,Fractured Arm,X-Ray and Splint,500,1,No,Recovered,5
3,4,75,Male,Stroke,CT Scan and Medication,10000,7,Yes,Stable,2
4,5,50,Female,Cancer,Surgery and Chemotherapy,25000,10,No,Recovered,4

**Check Dataset Info**

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 984 entries, 0 to 983
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Patient_ID      984 non-null    int64
 1   Age             984 non-null    int64
 2   Gender          984 non-null    object
 3   Condition       984 non-null    object
 4   Procedure       984 non-null    object
 5   Cost            984 non-null    int64
 6   Length_of_Stay  984 non-null    int64
 7   Readmission     984 non-null    object
 8   Outcome         984 non-null    object
 9   Satisfaction    984 non-null    int64
dtypes: int64(5), object(5)
memory usage: 77.0+ KB

Find Duplicate Rows

In [6]:
df.duplicated().sum()

np.int64(0)

View Duplicate Rows

In [7]:
df[df.duplicated()]

Empty DataFrame
Columns: [Patient_ID, Age, Gender, Condition, Procedure, Cost, Length_of_Stay, Readmission, Outcome, Satisfaction]
Index: []

Remove Duplicate Rows

In [8]:
df_cleaned = df.drop_duplicates()

Save Cleaned Data

In [9]:
df_cleaned.to_excel('cleaned_hospital_data.xlsx', index=False)